### ISSUE TITLE
Program fails if you don't have the directory ~/Documents

### ISSUE THREAD

**Issue by pockethook** [syncfast/clockwise#4] opened 2021-07-29 16:58 UTC
Perhaps this should be a configuration parameter and perhaps it should default to somewhere else like /tmp?

**Comment by droctothorpe** [comment] 2021-07-30 14:36
Duplicate of https://github.com/syncfast/clockwise/issues/6.

Thanks for the feedback, @pockethook. This is a great suggestion.

**Closed by droctothorpe** 2021-07-30 14:36 UTC
Labels: duplicate
